<?php $this->layout('layout::default', $this->data()) ?>

<?php $this->start('javascript') ?>
    <script>
        $('#form-resources').on('submit', function (event) {
            event.preventDefault();
            location.assign('/resources/' + $('select[name=resources]').val());
        });
    </script>
<?php $this->stop() ?>

<h1 class="mt-3">OpenStreetMap Community Index</h1>
<h2>Resources</h2>
<hr>
<form id="form-resources" autocomplete="off">
    <div class="input-group mb-3">
        <select class="form-control" name="resources">
<?php foreach ($resources as $group => $countries) : ?>
            <optgroup label="<?=$this->e($group, 'ucfirst')?>">

<?php if (empty($countries)) : ?>
                <option value="<?=$this->e($group)?>/<?=$this->e($group)?>"><?=$this->e($group, 'ucfirst')?></option>
<?php else : ?>

<?php foreach ($countries as $country) : ?>
<?php if (is_array($country)) : ?>
                <option value="<?=$this->e($group)?>/<?=$this->e($country[0])?>"><?=$this->e($country[1], 'ucfirst')?></option>
<?php else : ?>
                <option value="<?=$this->e($group)?>/<?=$this->e($country)?>"><?=$this->e($country, 'ucfirst')?></option>
<?php endif ?>
<?php endforeach ?>

<?php endif ?>

            </optgroup>
<?php endforeach ?>
        </select>
        <div class="input-group-append">
            <button class="btn btn-outline-primary" type="submit">Go</button>
        </div>
    </div>
</form>
