<?php $this->layout('layout::default', $this->data()) ?>

<?php $this->start('stylesheet') ?>
    <style>
        h2 > svg {
            height: 0.9rem;
        }
    </style>
<?php $this->stop() ?>

<?php if ($iframe === false) : ?>
    <h1 class="mt-3"><?=$this->e($country, 'ucfirst')?></h1>
    <hr>
<?php endif ?>

<ul class="list-group my-3">
<?php foreach ($resources as $id => $resource) : ?>
    <li class="list-group-item">
        <div class="d-flex w-100 justify-content-between">
            <h2 class="h5 mb-1">
<?php if (!is_null($resource->image)) : ?>
                <?=$resource->image?>
<?php endif ?>
                <a href="<?=$resource->url?>" target="_blank">
                    <?=$this->e($resource->name)?>
                </a>
            </h2>
<?php if (!empty($resource->languages)) : ?>
            <div>
<?php foreach ($resource->languages as $code => $language) : ?>
                <span class="badge badge-secondary" title="<?=$this->e($language)?>" style="cursor: help;"><?=$this->e($code)?></span>
<?php endforeach ?>
            </div>
<?php endif ?>
        </div>
        <p class="mb-1"><?=$this->e($resource->description)?></p>
<?php if (!empty($resource->extendedDescription)) : ?>
        <small><?=$this->e($resource->extendedDescription)?></small>
<?php endif ?>
    </li>
<?php endforeach ?>
</ul>
