version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
    groups:
      babel:
        applies-to: version-updates
        patterns:
          - "@babel/*"
      eslint:
        applies-to: version-updates
        patterns:
          - "@eslint*"
          - "eslint*"
      rollup:
        applies-to: version-updates
        patterns:
          - "@rollup/*"
          - "rollup*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
