env:
  browser: true
  es6: true
extends:
  - standard
  - eslint:recommended
  - prettier
plugins:
  - svelte3
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2020
  sourceType: module
overrides: [{ "files": ["**/*.svelte"], "processor": "svelte3/svelte3" }]
rules: {}
